---
- name: restart ivr6
  command: 'service {{ appname }} start'
  when: ansible_distribution_major_version == "6"
- name: restart ivr7
  systemd: name={{ appname }} state=restarted
  when: ansible_distribution_major_version == "7"
- name: rsyslog
  systemd: name=rsyslog state=restarted